# Generated by Django 6.0.6 on 2026-06-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scripture_reference', models.CharField(max_length=100)),
                ('scripture_text', models.TextField()),
                ('reflection', models.TextField()),
                ('prayer', models.TextField()),
                ('application', models.TextField(blank=True)),
                ('key_takeaway', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, default='Godfident', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devotionals',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevotionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Devotional Categories',
                'db_table': 'devotional_categories',
            },
        ),
        migrations.CreateModel(
            name='DailyDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='devotionals.devotional')),
            ],
            options={
                'db_table': 'daily_devotionals',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='devotional',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devotionals', to='devotionals.devotionalcategory'),
        ),
        migrations.CreateModel(
            name='DevotionalReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devotionals.devotional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devotional_read_history',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'devotional')},
            },
        ),
        migrations.CreateModel(
            name='SavedDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('devotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='devotionals.devotional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_devotionals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_devotionals',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'devotional')},
            },
        ),
    ]
