# Generated by Django 6.0.6 on 2026-06-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Prayer Categories',
                'db_table': 'prayer_categories',
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_type', models.CharField(choices=[('request', 'Prayer Request'), ('praise', 'Praise Report'), ('intercession', 'Intercession'), ('thanksgiving', 'Thanksgiving')], default='request', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('scripture', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('answered', 'Answered'), ('archived', 'Archived')], default='active', max_length=20)),
                ('answered_note', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayers', to='prayer.prayercategory')),
            ],
            options={
                'db_table': 'prayers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('prayed_at', models.DateTimeField(auto_now_add=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prayer.prayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_logs',
                'ordering': ['-prayed_at'],
            },
        ),
    ]
