# Generated by Django 5.0.6 on 2026-07-26 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('scripture', models.CharField(blank=True, max_length=200)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_journals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_prayer_date', models.DateField(blank=True, null=True)),
                ('total_days_prayed', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_streaks',
            },
        ),
        migrations.CreateModel(
            name='PrayerTimerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_timer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_timer_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
