# Generated by Django 6.1.1 on 2026-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0002_prayerjournal_prayersession_prayerstreak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayersession",
            name="planned_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
