# Generated by Django 6.0.6 on 2026-06-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2)),
                ('chapter_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'bible_books',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='BibleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bible_translations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VerseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verse_notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblebook')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.bibletranslation')),
            ],
            options={
                'db_table': 'bible_verses',
                'indexes': [models.Index(fields=['translation', 'book', 'chapter'], name='bible_verse_transla_7a544c_idx'), models.Index(fields=['translation', 'book', 'chapter', 'verse'], name='bible_verse_transla_1d45fb_idx')],
                'unique_together': {('translation', 'book', 'chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book', 'chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chapter', models.PositiveSmallIntegerField()),
                ('from_verse', models.PositiveSmallIntegerField()),
                ('to_chapter', models.PositiveSmallIntegerField()),
                ('to_verse', models.PositiveSmallIntegerField()),
                ('to_verse_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('from_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_refs_from', to='bible.biblebook')),
                ('to_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_refs_to', to='bible.biblebook')),
            ],
            options={
                'db_table': 'cross_references',
                'indexes': [models.Index(fields=['from_book', 'from_chapter', 'from_verse'], name='cross_refer_from_bo_48641e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('orange', 'Orange')], default='yellow', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'highlights',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book', 'chapter', 'verse')},
            },
        ),
    ]
