# Generated by Django 6.1.1 on 2026-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0003_focusschedule_presets"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="purpose",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
