# Generated by Django 6.0.6 on 2026-06-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('chronological', 'Chronological'), ('canonical', 'Canonical (Book by Book)'), ('thematic', 'Thematic'), ('gospel', 'Gospels Focus'), ('nt', 'New Testament'), ('ot', 'Old Testament'), ('proverbs', 'Proverbs'), ('psalms', 'Psalms'), ('custom', 'Custom')], max_length=20)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_plans',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('readings', models.JSONField(default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='readingplans.readingplan')),
            ],
            options={
                'db_table': 'reading_plan_days',
                'ordering': ['day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('total_days_read', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_streaks',
            },
        ),
        migrations.CreateModel(
            name='UserReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_day', models.PositiveSmallIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='readingplans.readingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_reading_plans',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='DayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readingplans.readingplanday')),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_progress', to='readingplans.userreadingplan')),
            ],
            options={
                'db_table': 'day_progress',
                'unique_together': {('user_plan', 'plan_day')},
            },
        ),
    ]
