# Generated by Django 5.0.6 on 2026-07-26 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_streak', models.PositiveIntegerField(default=0)),
                ('prayer_streak', models.PositiveIntegerField(default=0)),
                ('focus_streak', models.PositiveIntegerField(default=0)),
                ('total_reading_minutes', models.PositiveIntegerField(default=0)),
                ('total_prayer_minutes', models.PositiveIntegerField(default=0)),
                ('total_focus_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_stats',
            },
        ),
    ]
