# Generated by Django 6.0.6 on 2026-06-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chapters_read', models.PositiveSmallIntegerField(default=0)),
                ('prayers_logged', models.PositiveSmallIntegerField(default=0)),
                ('devotionals_read', models.PositiveSmallIntegerField(default=0)),
                ('ai_interactions', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('translation', models.CharField(default='KJV', max_length=10)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_activities',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='reading_act_user_id_c18ca7_idx')],
            },
        ),
    ]
