# Generated by Django 5.0.6 on 2026-07-26 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='focus_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='notes_created',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='prayer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='reminders_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='rules_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_time_seconds', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('most_visited_page', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_usage',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
