# Generated by Django 5.0.6 on 2026-07-30 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulecategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Rule Categories'},
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['user', 'is_archived'], name='rules_user_id_f1da28_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['user', 'category'], name='rules_user_id_8b50ae_idx'),
        ),
    ]
