# Generated by Django 5.0.6 on 2026-07-26 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('devotional', 'Daily Devotional'), ('reading_reminder', 'Reading Reminder'), ('prayer_reminder', 'Prayer Reminder'), ('streak', 'Streak Update'), ('plan_complete', 'Plan Completed'), ('reminder', 'Reminder'), ('general', 'General'), ('achievement', 'Achievement Unlocked')], max_length=30),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('token', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_devices',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
